const easy_questions = [
  {
    question: "What is the speed of light?",
    subject: "Physics",
    topic: "Waves",
    difficulty: "Easy",
    marks: 3,
  },
  {
    question: "Name the planets in our solar system.",
    subject: "Astronomy",
    topic: "Solar System",
    difficulty: "Easy",
    marks: 4,
  },
  {
    question: "Solve the equation 2x + 5 = 15.",
    subject: "Mathematics",
    topic: "Algebra",
    difficulty: "Easy",
    marks: 1,
  },
  {
    question: "What is the chemical formula for water?",
    subject: "Chemistry",
    topic: "Chemical Formulas",
    difficulty: "Easy",
    marks: 2,
  },
  {
    question: "Who is the author of 'Romeo and Juliet'?",
    subject: "Literature",
    topic: "Shakespeare",
    difficulty: "Easy",
    marks: 3,
  },
  {
    question: "What is the capital of France?",
    subject: "Geography",
    topic: "World Capitals",
    difficulty: "Easy",
    marks: 2,
  },
  {
    question: "Name the process by which plants make their own food.",
    subject: "Biology",
    topic: "Botany",
    difficulty: "Easy",
    marks: 6,
  },
  {
    question: "What is the Pythagorean theorem?",
    subject: "Mathematics",
    topic: "Geometry",
    difficulty: "Easy",
    marks: 4,
  },
  {
    question: "Name the three states of matter.",
    subject: "Chemistry",
    topic: "States of Matter",
    difficulty: "Easy",
    marks: 3,
  },
  {
    question: "Who painted the Mona Lisa?",
    subject: "Art",
    topic: "Renaissance Art",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "What is the capital of Japan?",
    subject: "Geography",
    topic: "World Capitals",
    difficulty: "Easy",
    marks: 2,
  },
  {
    question: "Who wrote 'To Kill a Mockingbird'?",
    subject: "Literature",
    topic: "Harper Lee",
    difficulty: "Easy",
    marks: 3,
  },
  {
    question: "What is the formula for calculating density?",
    subject: "Physics",
    topic: "Density",
    difficulty: "Easy",
    marks: 3,
  },
  {
    question: "Name the largest ocean on Earth.",
    subject: "Geography",
    topic: "Oceans",
    difficulty: "Easy",
    marks: 4,
  },
  {
    question: "Who discovered electricity?",
    subject: "Physics",
    topic: "Electricity",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "Name the seven continents.",
    subject: "Geography",
    topic: "Continents",
    difficulty: "Easy",
    marks: 3,
  },
  {
    question: "What is the formula for the area of a circle?",
    subject: "Mathematics",
    topic: "Geometry",
    difficulty: "Easy",
    marks: 4,
  },
  {
    question: "What is the role of red blood cells in the human body?",
    subject: "Biology",
    topic: "Human Anatomy",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question:
      "Name the process by which rocks are broken down into smaller particles.",
    subject: "Geology",
    topic: "Weathering",
    difficulty: "Easy",
    marks: 3,
  },
  {
    question: "Solve the quadratic equation: x^2 - 4x + 4 = 0.",
    subject: "Mathematics",
    topic: "Algebra",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "Who wrote '1984'?",
    subject: "Literature",
    topic: "George Orwell",
    difficulty: "Easy",
    marks: 3,
  },
  {
    question: "What is the law of conservation of energy?",
    subject: "Physics",
    topic: "Energy",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "Name the largest desert in the world.",
    subject: "Geography",
    topic: "Deserts",
    difficulty: "Easy",
    marks: 3,
  },
  {
    question: "What is the role of the nervous system in the human body?",
    subject: "Biology",
    topic: "Human Anatomy",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "What is Hooke's Law?",
    subject: "Physics",
    topic: "Mechanics",
    difficulty: "Easy",
    marks: 3,
  },
  {
    question: "Name the five senses of the human body.",
    subject: "Biology",
    topic: "Human Anatomy",
    difficulty: "Easy",
    marks: 4,
  },
  {
    question: "Evaluate the expression: 3^4 - 2(5 + 1).",
    subject: "Mathematics",
    topic: "Algebra",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "Who painted 'Starry Night'?",
    subject: "Art",
    topic: "Vincent van Gogh",
    difficulty: "Easy",
    marks: 3,
  },
  {
    question: "What is the function of the endoplasmic reticulum in a cell?",
    subject: "Biology",
    topic: "Cell Biology",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "Name the four layers of the Earth.",
    subject: "Geology",
    topic: "Earth's Layers",
    difficulty: "Easy",
    marks: 3,
  },
  {
    question: "Solve the logarithmic equation: log₂(x) = 3.",
    subject: "Mathematics",
    topic: "Algebra",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "Who wrote 'Pride and Prejudice'?",
    subject: "Literature",
    topic: "Jane Austen",
    difficulty: "Easy",
    marks: 3,
  },
  {
    question: "What is the law of conservation of mass?",
    subject: "Chemistry",
    topic: "Chemical Reactions",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "Name the highest mountain in the world.",
    subject: "Geography",
    topic: "Mountains",
    difficulty: "Easy",
    marks: 3,
  },
  {
    question: "What is the function of the Golgi apparatus in a cell?",
    subject: "Biology",
    topic: "Cell Biology",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question:
      "Find the solution to the system of inequalities: y > 2x - 1, 3x + y < 6.",
    subject: "Mathematics",
    topic: "Algebra",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "Who wrote 'The Great Gatsby'?",
    subject: "Literature",
    topic: "F. Scott Fitzgerald",
    difficulty: "Easy",
    marks: 3,
  },
  {
    question: "What is Ohm's Law?",
    subject: "Physics",
    topic: "Electricity",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "Name the longest river in the world.",
    subject: "Geography",
    topic: "Rivers",
    difficulty: "Easy",
    marks: 3,
  },
  {
    question: "What is the function of the cell membrane?",
    subject: "Biology",
    topic: "Cell Biology",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question:
      "Name the process by which rocks are formed from pre-existing rocks.",
    subject: "Geology",
    topic: "Rock Cycle",
    difficulty: "Easy",
    marks: 3,
  },
  {
    question: "Solve the system of equations: 4x - 2y = 10, 2x + y = 6.",
    subject: "Mathematics",
    topic: "Systems of Equations",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "Who painted 'The Last Supper'?",
    subject: "Art",
    topic: "Leonardo da Vinci",
    difficulty: "Easy",
    marks: 3,
  },
  {
    question: "Solve the equation: 2a + 3 = 11.",
    subject: "Mathematics",
    topic: "Algebra",
    difficulty: "Easy",
    marks: 3,
  },
  {
    question: "What is the function of the mitochondria in a cell?",
    subject: "Biology",
    topic: "Cell Biology",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "What is the currency of India?",
    subject: "Economics",
    topic: "Currencies",
    difficulty: "Easy",
    marks: 3,
  },
  {
    question: "Who wrote 'Pride and Prejudice'?",
    subject: "Literature",
    topic: "British Literature",
    difficulty: "Easy",
    marks: 3,
  },
  {
    question: "Simplify the expression: 4a - (2b + 3a) + 5b.",
    subject: "Mathematics",
    topic: "Algebra",
    difficulty: "Easy",
    marks: 3,
  },
  {
    question: "What is the capital of Australia?",
    subject: "Geography",
    topic: "World Capitals",
    difficulty: "Easy",
    marks: 2,
  },
  {
    question: "What is the capital of Canada?",
    subject: "Geography",
    topic: "World Capitals",
    difficulty: "Easy",
    marks: 2,
  },
  {
    question: "Who wrote 'Romeo and Juliet'?",
    subject: "Literature",
    topic: "Shakespeare",
    difficulty: "Easy",
    marks: 1,
  },
  {
    question: "What is the square root of 25?",
    subject: "Mathematics",
    topic: "Algebra",
    difficulty: "Easy",
    marks: 1,
  },
  {
    question: "Name the largest mammal on Earth.",
    subject: "Biology",
    topic: "Zoology",
    difficulty: "Easy",
    marks: 2,
  },
  {
    question: "In which year did Christopher Columbus reach the Americas?",
    subject: "History",
    topic: "Exploration",
    difficulty: "Easy",
    marks: 2,
  },
  {
    question: "What is the chemical symbol for gold?",
    subject: "Chemistry",
    topic: "Elements",
    difficulty: "Easy",
    marks: 1,
  },
  {
    question: "Who is the current President of the United States?",
    subject: "Political Science",
    topic: "Government",
    difficulty: "Easy",
    marks: 1,
  },
  {
    question: "What is the smallest prime number?",
    subject: "Mathematics",
    topic: "Number Theory",
    difficulty: "Easy",
    marks: 1,
  },
  {
    question: "Name the first man to step on the Moon.",
    subject: "Astronomy",
    topic: "Space Exploration",
    difficulty: "Easy",
    marks: 2,
  },
  {
    question: "What is the formula for the area of a rectangle?",
    subject: "Mathematics",
    topic: "Geometry",
    difficulty: "Easy",
    marks: 1,
  },
  {
    question: "Who painted the 'Starry Night'?",
    subject: "Art",
    topic: "Art History",
    difficulty: "Easy",
    marks: 2,
  },
  {
    question: "What is the main gas in the Earth's atmosphere?",
    subject: "Environmental Science",
    topic: "Atmosphere",
    difficulty: "Easy",
    marks: 2,
  },
  {
    question: "What is the capital of Brazil?",
    subject: "Geography",
    topic: "World Capitals",
    difficulty: "Easy",
    marks: 1,
  },
  {
    question: "Solve the equation: 3 + x = 7.",
    subject: "Mathematics",
    topic: "Algebra",
    difficulty: "Easy",
    marks: 1,
  },
  {
    question: "Who wrote 'Hamlet'?",
    subject: "Literature",
    topic: "Shakespeare",
    difficulty: "Easy",
    marks: 2,
  },
  {
    question:
      "What is the process of converting water vapor to liquid water called?",
    subject: "Environmental Science",
    topic: "Water Cycle",
    difficulty: "Easy",
    marks: 2,
  },
  {
    question: "How many sides does a hexagon have?",
    subject: "Mathematics",
    topic: "Geometry",
    difficulty: "Easy",
    marks: 1,
  },
  {
    question: "Name the currency of China.",
    subject: "Economics",
    topic: "Currencies",
    difficulty: "Easy",
    marks: 1,
  },
  {
    question: "Who wrote 'The Great Gatsby'?",
    subject: "Literature",
    topic: "American Literature",
    difficulty: "Easy",
    marks: 2,
  },
  {
    question: "What is the largest organ in the human body?",
    subject: "Biology",
    topic: "Human Anatomy",
    difficulty: "Easy",
    marks: 2,
  },
  {
    question: "What is the formula for the perimeter of a square?",
    subject: "Mathematics",
    topic: "Geometry",
    difficulty: "Easy",
    marks: 1,
  },
  {
    question: "Name the process by which plants make their own food.",
    subject: "Biology",
    topic: "Botany",
    difficulty: "Easy",
    marks: 2,
  },
  {
    question: "Who is known as the 'Father of Modern Science'?",
    subject: "Scientists",
    topic: "Scientific Discoveries",
    difficulty: "Easy",
    marks: 1,
  },
  {
    question: "What is the melting point of ice in Celsius?",
    subject: "Chemistry",
    topic: "Physical Chemistry",
    difficulty: "Easy",
    marks: 1,
  },
  {
    question: "Who is the author of '1984'?",
    subject: "Literature",
    topic: "Dystopian Fiction",
    difficulty: "Easy",
    marks: 2,
  },
  {
    question: "What is the largest desert in the world?",
    subject: "Geography",
    topic: "Deserts",
    difficulty: "Easy",
    marks: 1,
  },
  {
    question: "What is the symbol for the element oxygen?",
    subject: "Chemistry",
    topic: "Elements",
    difficulty: "Easy",
    marks: 2,
  },
  {
    question: "How many continents are there in the world?",
    subject: "Geography",
    topic: "Continents",
    difficulty: "Easy",
    marks: 1,
  },
  {
    question: "What is the capital of South Africa?",
    subject: "Geography",
    topic: "World Capitals",
    difficulty: "Easy",
    marks: 1,
  },
  {
    question: "Simplify the expression: 2(x + 3).",
    subject: "Mathematics",
    topic: "Algebra",
    difficulty: "Easy",
    marks: 1,
  },
  {
    question: "Who discovered penicillin?",
    subject: "Biology",
    topic: "Medicine",
    difficulty: "Easy",
    marks: 2,
  },
  {
    question: "What is the primary function of the liver?",
    subject: "Biology",
    topic: "Human Anatomy",
    difficulty: "Easy",
    marks: 1,
  },
  {
    question: "Name the third planet from the sun.",
    subject: "Astronomy",
    topic: "Solar System",
    difficulty: "Easy",
    marks: 1,
  },
  {
    question: "What is the capital of Russia?",
    subject: "Geography",
    topic: "World Capitals",
    difficulty: "Easy",
    marks: 2,
  },
  {
    question: "Define the term 'metamorphosis.'",
    subject: "Biology",
    topic: "Zoology",
    difficulty: "Easy",
    marks: 1,
  },
  {
    question: "What is the currency of Japan?",
    subject: "Economics",
    topic: "Currencies",
    difficulty: "Easy",
    marks: 2,
  },
  {
    question: "Who is the 'Father of Modern Psychology'?",
    subject: "Psychology",
    topic: "Psychologists",
    difficulty: "Easy",
    marks: 1,
  },
  {
    question: "What is the boiling point of water in Fahrenheit?",
    subject: "Chemistry",
    topic: "Physical Chemistry",
    difficulty: "Easy",
    marks: 2,
  },
  {
    question:
      "Name the process by which plants release water vapor into the atmosphere.",
    subject: "Environmental Science",
    topic: "Water Cycle",
    difficulty: "Easy",
    marks: 1,
  },
  {
    question: "What is the capital of China?",
    subject: "Geography",
    topic: "World Capitals",
    difficulty: "Easy",
    marks: 2,
  },
  {
    question: "Who wrote 'Macbeth'?",
    subject: "Literature",
    topic: "Shakespeare",
    difficulty: "Easy",
    marks: 1,
  },
  {
    question: "What is the chemical formula for table salt?",
    subject: "Chemistry",
    topic: "Chemical Formulas",
    difficulty: "Easy",
    marks: 2,
  },
  {
    question: "How many players are there on a standard soccer team?",
    subject: "Sports",
    topic: "Soccer",
    difficulty: "Easy",
    marks: 1,
  },
  {
    question: "What is the largest ocean on Earth?",
    subject: "Geography",
    topic: "Oceans",
    difficulty: "Easy",
    marks: 2,
  },
  {
    question: "Who is the author of 'The Catcher in the Rye'?",
    subject: "Literature",
    topic: "American Literature",
    difficulty: "Easy",
    marks: 1,
  },
  {
    question: "What is the formula for the volume of a cylinder?",
    subject: "Mathematics",
    topic: "Geometry",
    difficulty: "Easy",
    marks: 2,
  },
  {
    question: "Define the term 'ecosystem.'",
    subject: "Environmental Science",
    topic: "Ecology",
    difficulty: "Easy",
    marks: 1,
  },
  {
    question: "What is the capital of Italy?",
    subject: "Geography",
    topic: "World Capitals",
    difficulty: "Easy",
    marks: 2,
  },
  {
    question: "Who is the current Prime Minister of the United Kingdom?",
    subject: "Political Science",
    topic: "Government",
    difficulty: "Easy",
    marks: 1,
  },
  {
    question:
      "What is the process of converting sunlight into chemical energy in plants called?",
    subject: "Biology",
    topic: "Photosynthesis",
    difficulty: "Easy",
    marks: 2,
  },
  {
    question: "Name the first human to journey into space.",
    subject: "Astronomy",
    topic: "Space Exploration",
    difficulty: "Easy",
    marks: 1,
  },
  {
    question: "What is the capital of Spain?",
    subject: "Geography",
    topic: "World Capitals",
    difficulty: "Easy",
    marks: 2,
  },
  {
    question: "Solve the equation: 4y - 7 = 11.",
    subject: "Mathematics",
    topic: "Algebra",
    difficulty: "Easy",
    marks: 1,
  },
  {
    question: "Who is the 'Father of Modern Chemistry'?",
    subject: "Chemistry",
    topic: "Scientists",
    difficulty: "Easy",
    marks: 2,
  },
  {
    question: "What is the process of the Earth's rotation on its axis called?",
    subject: "Astronomy",
    topic: "Earth's Motion",
    difficulty: "Easy",
    marks: 1,
  },
  {
    question: "Name the smallest prime number.",
    subject: "Mathematics",
    topic: "Number Theory",
    difficulty: "Easy",
    marks: 2,
  },
  {
    question: "Who is the author of 'Frankenstein'?",
    subject: "Literature",
    topic: "Gothic Fiction",
    difficulty: "Easy",
    marks: 1,
  },
  {
    question: "What is the capital of Mexico?",
    subject: "Geography",
    topic: "World Capitals",
    difficulty: "Easy",
    marks: 2,
  },
  {
    question: "Define the term 'gravity.'",
    subject: "Physics",
    topic: "Gravity",
    difficulty: "Easy",
    marks: 1,
  },
  {
    question: "What is the main function of the large intestine?",
    subject: "Biology",
    topic: "Human Anatomy",
    difficulty: "Easy",
    marks: 2,
  },
  {
    question: "What is the currency of the United Kingdom?",
    subject: "Economics",
    topic: "Currencies",
    difficulty: "Easy",
    marks: 1,
  },
  {
    question: "Who is the author of 'War and Peace'?",
    subject: "Literature",
    topic: "Russian Literature",
    difficulty: "Easy",
    marks: 2,
  },
];

const medium_questions = [
  {
    question: "Define Newton's first law of motion.",
    subject: "Physics",
    topic: "Mechanics",
    difficulty: "Medium",
    marks: 3,
  },
  {
    question: "Explain the process of photosynthesis.",
    subject: "Biology",
    topic: "Botany",
    difficulty: "Medium",
    marks: 4,
  },
  {
    question: "Define GDP (Gross Domestic Product).",
    subject: "Economics",
    topic: "Macroeconomics",
    difficulty: "Medium",
    marks: 4,
  },
  {
    question: "Who discovered penicillin?",
    subject: "Biology",
    topic: "Medicine",
    difficulty: "Medium",
    marks: 3,
  },
  {
    question: "Define the concept of supply and demand.",
    subject: "Economics",
    topic: "Microeconomics",
    difficulty: "Medium",
    marks: 4,
  },
  {
    question: "Simplify the expression: 3(x + 2) - 2(3 - x).",
    subject: "Mathematics",
    topic: "Algebra",
    difficulty: "Medium",
    marks: 4,
  },
  {
    question: "What is the structure of an atom?",
    subject: "Chemistry",
    topic: "Atomic Structure",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "Explain the concept of natural selection.",
    subject: "Biology",
    topic: "Evolution",
    difficulty: "Medium",
    marks: 4,
  },
  {
    question: "Solve the system of equations: 2x + y = 5, 3x - 2y = 8.",
    subject: "Mathematics",
    topic: "Systems of Equations",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question:
      "What is the difference between a covalent bond and an ionic bond?",
    subject: "Chemistry",
    topic: "Chemical Bonds",
    difficulty: "Medium",
    marks: 4,
  },
  {
    question: "Define the concept of inflation.",
    subject: "Economics",
    topic: "Macroeconomics",
    difficulty: "Medium",
    marks: 4,
  },
  {
    question: "Who is known as the 'Father of Modern Physics'?",
    subject: "Physics",
    topic: "Scientists",
    difficulty: "Medium",
    marks: 4,
  },
  {
    question: "What is the greenhouse effect?",
    subject: "Environmental Science",
    topic: "Climate Change",
    difficulty: "Medium",
    marks: 4,
  },
  {
    question: "What is the role of the mitochondria in a cell?",
    subject: "Biology",
    topic: "Cell Biology",
    difficulty: "Medium",
    marks: 4,
  },
  {
    question: "Define the concept of opportunity cost.",
    subject: "Economics",
    topic: "Microeconomics",
    difficulty: "Medium",
    marks: 4,
  },
  {
    question: "Who discovered the structure of DNA?",
    subject: "Biology",
    topic: "Genetics",
    difficulty: "Medium",
    marks: 4,
  },
  {
    question: "What is the difference between weather and climate?",
    subject: "Environmental Science",
    topic: "Weather and Climate",
    difficulty: "Medium",
    marks: 4,
  },
  {
    question: "What is the structure of the Earth's atmosphere?",
    subject: "Geography",
    topic: "Atmosphere",
    difficulty: "Medium",
    marks: 4,
  },
  {
    question: "Define the concept of elasticity in economics.",
    subject: "Economics",
    topic: "Microeconomics",
    difficulty: "Medium",
    marks: 4,
  },
  {
    question: "Who developed the theory of relativity?",
    subject: "Physics",
    topic: "Albert Einstein",
    difficulty: "Medium",
    marks: 4,
  },
  {
    question: "Explain the concept of sustainable development.",
    subject: "Environmental Science",
    topic: "Sustainability",
    difficulty: "Medium",
    marks: 4,
  },
  {
    question: "What is the role of ribosomes in a cell?",
    subject: "Biology",
    topic: "Cell Biology",
    difficulty: "Medium",
    marks: 4,
  },
  {
    question: "Define the concept of monopoly in economics.",
    subject: "Economics",
    topic: "Microeconomics",
    difficulty: "Medium",
    marks: 4,
  },
  {
    question: "Who proposed the theory of continental drift?",
    subject: "Geology",
    topic: "Plate Tectonics",
    difficulty: "Medium",
    marks: 4,
  },
  {
    question: "Explain the concept of biodiversity.",
    subject: "Environmental Science",
    topic: "Biodiversity",
    difficulty: "Medium",
    marks: 4,
  },
  {
    question: "What is the role of the lysosomes in a cell?",
    subject: "Biology",
    topic: "Cell Biology",
    difficulty: "Medium",
    marks: 4,
  },
  {
    question: "Define the concept of oligopoly in economics.",
    subject: "Economics",
    topic: "Microeconomics",
    difficulty: "Medium",
    marks: 4,
  },
  {
    question: "Who formulated the laws of motion?",
    subject: "Physics",
    topic: "Mechanics",
    difficulty: "Medium",
    marks: 4,
  },
  {
    question: "Explain the concept of acid rain.",
    subject: "Environmental Science",
    topic: "Air Pollution",
    difficulty: "Medium",
    marks: 4,
  },
  {
    question: "What is the composition of the Earth's core?",
    subject: "Geology",
    topic: "Earth's Core",
    difficulty: "Medium",
    marks: 4,
  },
  {
    question: "Name the three branches of the United States government.",
    subject: "Political Science",
    topic: "Government",
    difficulty: "Medium",
    marks: 4,
  },
  {
    question: "Who is known as the 'Father of Modern Physics'?",
    subject: "Physics",
    topic: "Scientists",
    difficulty: "Medium",
    marks: 4,
  },
  {
    question: "What is the role of hemoglobin in the human body?",
    subject: "Biology",
    topic: "Human Anatomy",
    difficulty: "Medium",
    marks: 4,
  },
  {
    question: "What is the process of nuclear fission?",
    subject: "Physics",
    topic: "Nuclear Physics",
    difficulty: "Medium",
    marks: 4,
  },
  {
    question: "Name the five senses of the human body.",
    subject: "Biology",
    topic: "Human Anatomy",
    difficulty: "Medium",
    marks: 4,
  },
  {
    question: "Who discovered the theory of relativity?",
    subject: "Physics",
    topic: "Scientists",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "Define the term 'Habeas Corpus.'",
    subject: "Law",
    topic: "Legal Terms",
    difficulty: "Medium",
    marks: 4,
  },
];

const hard_questions = [
  {
    question: "Explain the concept of quantum entanglement.",
    subject: "Physics",
    topic: "Quantum Mechanics",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "Derive the formula for the area of a circle.",
    subject: "Mathematics",
    topic: "Geometry",
    difficulty: "Hard",
    marks: 4,
  },
  {
    question: "Discuss the impact of climate change on biodiversity.",
    subject: "Environmental Science",
    topic: "Climate Change",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question:
      "Examine the causes and consequences of the Industrial Revolution.",
    subject: "History",
    topic: "Industrial Revolution",
    difficulty: "Hard",
    marks: 4,
  },
  {
    question: "Elaborate on the process of DNA replication.",
    subject: "Biology",
    topic: "Genetics",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "Solve the system of equations: 3x + 2y = 10 and 2x - y = 4.",
    subject: "Mathematics",
    topic: "Algebra",
    difficulty: "Hard",
    marks: 4,
  },
  {
    question: "Analyze the economic implications of globalization.",
    subject: "Economics",
    topic: "Globalization",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question:
      "Explore the role of neurotransmitters in the human nervous system.",
    subject: "Biology",
    topic: "Neuroscience",
    difficulty: "Hard",
    marks: 4,
  },
  {
    question: "Evaluate the impact of artificial intelligence on society.",
    subject: "Technology",
    topic: "Artificial Intelligence",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "Prove Fermat's Last Theorem.",
    subject: "Mathematics",
    topic: "Number Theory",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question:
      "Examine the process of stellar nucleosynthesis in the life cycle of stars.",
    subject: "Astronomy",
    topic: "Astrophysics",
    difficulty: "Hard",
    marks: 4,
  },
  {
    question:
      "Discuss the philosophical implications of the 'Trolley Problem' in ethics.",
    subject: "Philosophy",
    topic: "Ethics",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "Explain the concept of dark matter in the universe.",
    subject: "Physics",
    topic: "Cosmology",
    difficulty: "Hard",
    marks: 4,
  },
  {
    question:
      "Analyze the impact of the Green Revolution on global agriculture.",
    subject: "Agriculture",
    topic: "Green Revolution",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "Derive the equation for the velocity of an object in free fall.",
    subject: "Physics",
    topic: "Kinematics",
    difficulty: "Hard",
    marks: 4,
  },
  {
    question: "Discuss the historical development of the theory of evolution.",
    subject: "Biology",
    topic: "Evolution",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "Examine the economic theories of John Maynard Keynes.",
    subject: "Economics",
    topic: "Keynesian Economics",
    difficulty: "Hard",
    marks: 4,
  },
  {
    question: "Evaluate the ethical implications of gene editing technologies.",
    subject: "Bioethics",
    topic: "Genetic Engineering",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "Prove the Pythagorean theorem.",
    subject: "Mathematics",
    topic: "Geometry",
    difficulty: "Hard",
    marks: 4,
  },
  {
    question:
      "Discuss the impact of the Gutenberg printing press on the Renaissance.",
    subject: "History",
    topic: "Renaissance",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "Examine the role of mitochondria in cellular energy production.",
    subject: "Biology",
    topic: "Cell Biology",
    difficulty: "Hard",
    marks: 4,
  },
  {
    question: "Analyze the economic factors contributing to income inequality.",
    subject: "Economics",
    topic: "Income Inequality",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "Discuss the political theories of Thomas Hobbes and John Locke.",
    subject: "Political Science",
    topic: "Political Philosophy",
    difficulty: "Hard",
    marks: 4,
  },
  {
    question: "Explain the principles of quantum computing.",
    subject: "Computer Science",
    topic: "Quantum Computing",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "Derive the formula for the volume of a cone.",
    subject: "Mathematics",
    topic: "Geometry",
    difficulty: "Hard",
    marks: 4,
  },
  {
    question: "Analyze the causes and consequences of the Great Depression.",
    subject: "History",
    topic: "Great Depression",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "Examine the role of enzymes in biological reactions.",
    subject: "Biology",
    topic: "Biochemistry",
    difficulty: "Hard",
    marks: 4,
  },
  {
    question: "Discuss the economic impact of renewable energy technologies.",
    subject: "Economics",
    topic: "Renewable Energy",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "Prove the divergence theorem in vector calculus.",
    subject: "Mathematics",
    topic: "Vector Calculus",
    difficulty: "Hard",
    marks: 4,
  },
  {
    question:
      "Analyze the political and social consequences of the French Revolution.",
    subject: "History",
    topic: "French Revolution",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "Examine the principles of game theory in economics.",
    subject: "Economics",
    topic: "Game Theory",
    difficulty: "Hard",
    marks: 4,
  },
  {
    question:
      "Discuss the ethical implications of artificial intelligence in healthcare.",
    subject: "Bioethics",
    topic: "Artificial Intelligence",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question:
      "Derive the equations of motion for a particle in a magnetic field.",
    subject: "Physics",
    topic: "Electromagnetism",
    difficulty: "Hard",
    marks: 4,
  },
  {
    question: "Analyze the impact of the internet on global communication.",
    subject: "Communication Studies",
    topic: "Internet Studies",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "Examine the ethical issues surrounding human cloning.",
    subject: "Bioethics",
    topic: "Cloning",
    difficulty: "Hard",
    marks: 4,
  },
];

const questions = {
  easy_questions,
  medium_questions,
  hard_questions,
};
module.exports = questions;
